version: '3'
services:
  backend:
    build: backend
    restart: unless-stopped
    environment:
      - DATABASE_URL=sqlite:////tmp/app.db
      - UPLOAD_DIRECTORY=/tmp
      - SECRET_KEY=secret
      - DEBUG=True
      - USER_ID=1
      - USER_USERNAME=user
      - USER_PASSWORD=passwd
    ports:
      - "8001:8000"
    expose:
      - 8000
    command: bash -c "poetry run python init_db.py && poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000"
  frontend:
    build: frontend
    restart: unless-stopped
    depends_on:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '8000:8000'
    command: 'bash -c "nginx -g ''daemon off;''"'
